front_client_index:
    path:     /
    defaults: { _controller: "ReclamationBundle:Reclamation:index" }
    methods:  GET

front_client_show:
    path:     /{id}/show
    defaults: { _controller: "ReclamationBundle:Reclamation:show" }
    methods:  GET

front_client_new:
    path:     /new
    defaults: { _controller: "ReclamationBundle:Reclamation:new" }
    methods:  [GET, POST]

front_client_edit:
    path:     /{id}/edit
    defaults: { _controller: "ReclamationBundle:Reclamation:edit" }
    methods:  [GET, POST]

front_client_delete:
    path:     /{id}/delete
    defaults: { _controller: "ReclamationBundle:Reclamation:delete" }
    methods:  DELETE
