users_listetravail:
    resource: "@UsersBundle/Resources/config/routing/listetravail.yml"
    prefix:     /

users_homepage:
    path:     /index
    defaults: { _controller: UsersBundle:Default:index }
users_Formulaire:
    path:     /back/admin/ajout
    defaults: { _controller: UsersBundle:Users:add }
users_supprimer:
    path:     /back/admin/delete/{id}
    defaults: { _controller: UsersBundle:Users:delete }
users_add:
    path:     /back/admin/add
    defaults: { _controller: UsersBundle:Users:add }
users_afficherJardinier:
    path:     /back/admin/afficheremp
    defaults: { _controller: UsersBundle:Users:Aficherstaff }
users_afficherAdmin:
    path:     /back/admin/afficherAdmin
    defaults: { _controller: UsersBundle:Users:AficherAdmin }
users_afficherPaysagiste:
    path:     /back/admin/afficherPaysagiste
    defaults: { _controller: UsersBundle:Users:AficherPaysagiste }
users_afficherExpert:
    path:     /back/admin/afficherExpert
    defaults: { _controller: UsersBundle:Users:AficherExpert }
users_afficherClients:
    path:     /back/admin/afficherClient
    defaults: { _controller: UsersBundle:Users:AficherClient }
users_ProfileAdmin:
    path:     /back/admin/ProfileAdmin
    defaults: { _controller: UsersBundle:Users:Profile }
users_ModifierAdmin:
    path:     /back/admin/ModifierAdmin
    defaults: { _controller: UsersBundle:Users:Profile }
users_ProfileExpert:
    path:     /back/expert/ProfileExpert
    defaults: { _controller: UsersBundle:Users:Profile }
users_ProfileJardinier:
    path:     /back/jardinier/ProfileJardinier
    defaults: { _controller: UsersBundle:Users:Profile }
users_ProfileClient:
    path:     /front/ProfileClient
    defaults: { _controller: UsersBundle:Users:Profile }
users_ProfilePaysagiste:
    path:     /back/paysagiste/ProfilePaysagiste
    defaults: { _controller: UsersBundle:Users:Profile }
calendrier_back:
    path:     /back/paysagiste/calendrier
    defaults: { _controller: UsersBundle:Users:calendrier }
calendrierJardinier_back:
    path:     /back/jardinier/calendrier
    defaults: { _controller: UsersBundle:Users:calendrier }
reserver_jardinier:
    path:     /front/reserverJardinier/{id}
    defaults: { _controller: UsersBundle:Users:reserver }

