listetravail_index:
    path:     /
    defaults: { _controller: "UsersBundle:ListeTravail:index" }
    methods:  GET

listetravail_show:
    path:     /show
    defaults: { _controller: "UsersBundle:ListeTravail:show" }

Jardinier_show:
    path:     /showJardinier
    defaults: { _controller: "UsersBundle:ListeTravail:AfficherJardinier" }

Paysagiste_show:
    path:     /showPaysagiste
    defaults: { _controller: "UsersBundle:ListeTravail:AfficherPaysagiste" }

Travail_affiche:
    path:     /showTravail/{id}
    defaults: { _controller: "UsersBundle:ListeTravail:showTravail" }

listetravail_new:
    path:     /new
    defaults: { _controller: "UsersBundle:ListeTravail:new" }
    methods:  [GET, POST]

listetravail_edit:
    path:     /edit/{id}
    defaults: { _controller: "UsersBundle:ListeTravail:edit" }
listetravail_modifier:
    path:     /modifier
    defaults: { _controller: "UsersBundle:ListeTravail:edit" }


listetravail_delete:
    path:     /delete/{id}
    defaults: { _controller: "UsersBundle:ListeTravail:delete" }

