back_expert_index:
    path:     /
    defaults: { _controller: "RecetteBundle:Recette:index" }
    methods:  GET

back_expert_show:
    path:     /{id}/show
    defaults: { _controller: "RecetteBundle:Recette:show" }
    methods:  GET

back_expert_new:
    path:     /new
    defaults: { _controller: "RecetteBundle:Recette:new" }
    methods:  [GET, POST]

back_expert_edit:
    path:     /{id}/edit
    defaults: { _controller: "RecetteBundle:Recette:edit" }
    methods:  [GET, POST]

back_expert_delete:
    path:     /{id}/delete
    defaults: { _controller: "RecetteBundle:Recette:delete" }
    methods:  DELETE
