offre_index:
    path:     /
    defaults: { _controller: "ProductBundle:OffrePromotion:index" }
    methods:  GET

offre_show:
    path:     /{id}/show
    defaults: { _controller: "ProductBundle:OffrePromotion:show" }
    methods:  GET

offre_new:
    path:     /new
    defaults: { _controller: "ProductBundle:OffrePromotion:new" }
    methods:  [GET, POST]

offre_edit:
    path:     /{id}/edit
    defaults: { _controller: "ProductBundle:OffrePromotion:edit" }
    methods:  [GET, POST]

offre_delete:
    path:     /{id}/delete
    defaults: { _controller: "ProductBundle:OffrePromotion:delete" }
    methods:  DELETE
